# Generated by Django 2.2 on 2021-10-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(default='media/new_icon.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
