# Generated by Django 2.2 on 2021-11-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211102_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_id', models.IntegerField()),
                ('receive_id', models.IntegerField()),
                ('msg', models.TextField()),
                ('is_delete', models.BooleanField(default=False)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
